#!/usr/bin/env python3
"""Render and validate the authoritative Rust/Mata parity matrix."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE = REPO_ROOT / "fevc/docs/rust_mata_parity.json"
OUTPUT = REPO_ROOT / "fevc/docs/RUST_MATA_PARITY.md"


def load() -> dict[str, object]:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    if document.get("schema_version") != 1:
        raise ValueError("unsupported parity schema")
    statuses = document.get("statuses")
    rows = document.get("rows")
    if not isinstance(statuses, list) or not all(
        isinstance(status, str) for status in statuses
    ):
        raise ValueError("parity statuses must be strings")
    if not isinstance(rows, list) or not rows:
        raise ValueError("parity rows must be a nonempty list")
    seen: set[str] = set()
    for row in rows:
        if not isinstance(row, dict):
            raise ValueError("parity rows must be objects")
        row_id = row.get("id")
        if not isinstance(row_id, str) or not row_id or row_id in seen:
            raise ValueError(f"invalid or duplicate parity row: {row_id!r}")
        seen.add(row_id)
        if row.get("mata") not in statuses or row.get("rust") not in statuses:
            raise ValueError(f"invalid parity status: {row_id}")
        if not isinstance(row.get("alpha_required"), bool):
            raise ValueError(f"invalid alpha requirement: {row_id}")
        for field in ("surface", "evidence"):
            if not isinstance(row.get(field), str) or not row[field]:
                raise ValueError(f"missing parity field {field}: {row_id}")
    return document


def render(document: dict[str, object]) -> str:
    rows = document["rows"]
    assert isinstance(rows, list)
    lines = [
        "# Rust/Mata parity matrix",
        "",
        "Generated from `rust_mata_parity.json`; do not edit this file by hand.",
        "Historical receipts remain source-bound and do not change these current statuses.",
        "",
        f"Target: `{document['release_target']}`. Updated: {document['updated']}.",
        "",
        "| Surface | Mata | Rust | Alpha gate | Current evidence or gap |",
        "|---|---|---|---:|---|",
    ]
    for row in rows:
        assert isinstance(row, dict)
        gate = "yes" if row["alpha_required"] else "no"
        lines.append(
            f"| {row['surface']} | {row['mata']} | {row['rust']} | "
            f"{gate} | {row['evidence']} |"
        )
    lines.extend(
        [
            "",
            "An alpha-required row is complete only when Rust is `qualified` on every",
            "claimed platform and the exact-source receipt is linked from the active plan.",
            "`implemented` means source exists but the release qualification is incomplete.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(load())
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
        return 0
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if current != rendered:
        print(f"generated parity matrix is stale: {OUTPUT.relative_to(REPO_ROOT)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
