"""Independent 120-digit literal-deletion oracle for the eight-row witness.

Inputs are frozen binary64 values; each deletion refits its original dummy
regression. No FEVC basis, projection, inverse, or correction code is called.
"""
from decimal import Decimal, localcontext
from pathlib import Path

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures/control_anchor_oracle.do"

INPUTS = [(-0.3528455767045989, -0.35425979026697196, -0.7071053669715708, 0.7042769398468247, 0.0), (-0.35425979026697196, -0.3528455767045989, -0.7071053669715708, 0.7099337940963171, 1.0916648104524687), (-0.35425979026697196, 0.3528455767045989, -0.00141421356237309, 1.4156249475055147, -0.05554110202683121), (-0.3528455767045989, 0.35425979026697196, 0.00141421356237309, 1.4127965203807686, -0.6258146823277324), (0.35425979026697196, -0.3528455767045989, 0.00141421356237309, -1.4156249475055147, 0.8941133511386081), (0.3528455767045989, -0.35425979026697196, -0.00141421356237309, -1.4127965203807686, 1.2984871126234903), (0.3528455767045989, 0.35425979026697196, 0.7071053669715708, -0.7042769398468247, -0.09987468759354223), (0.35425979026697196, 0.3528455767045989, 0.7071053669715708, -0.7099337940963171, 0.0818628877629668)]


def transpose(a):
    return [list(row) for row in zip(*a)]


def multiply(a, b):
    return [[sum((x*y for x,y in zip(row,col)),Decimal(0))
             for col in zip(*b)] for row in a]


def inverse(a):
    n=len(a)
    x=[list(row)+[Decimal(i==j) for j in range(n)] for i,row in enumerate(a)]
    for k in range(n):
        pivot=max(range(k,n),key=lambda i:abs(x[i][k]))
        x[k],x[pivot]=x[pivot],x[k]
        scale=x[k][k]
        x[k]=[v/scale for v in x[k]]
        for i in range(n):
            if i!=k:
                scale=x[i][k]
                x[i]=[u-scale*v for u,v in zip(x[i],x[k])]
    return [row[n:] for row in x]


def fit(x,y):
    return multiply(inverse(multiply(transpose(x),x)),multiply(transpose(x),y))


def quadratic(a,b):
    return multiply(multiply(transpose(b),a),b)[0][0]


def fixture_text(precision=120):
    lines=["// Generated by tests/oracles/control_anchor.py; exact stored-input oracle."]
    for i,row in enumerate(INPUTS,1):
        for name,value in zip(("order_z1","order_z2","order_u1","order_u2","y"),row):
            lines.append(f"quietly replace {name} = {value:.17g} in {i}")
    with localcontext() as context:
        context.prec=precision
        data=[[Decimal.from_float(v) for v in row] for row in INPUTS]
        n=len(data)
        y=[[row[4]] for row in data]
        d=[[Decimal(i<4),Decimal(i>=4)] for i in range(n)]
        f=[[Decimal(i//2%2==0)] for i in range(n)]
        h=[[Decimal(i==j)/n-Decimal(1)/(n*n) for j in range(n)] for i in range(n)]
        for basis,offset in [("z",0),("u",2)]:
            z=[row[offset:offset+2] for row in data]
            for nuisance in ("joint","fixedoffset"):
                x=[a+b+c for a,b,c in zip(d,f,z)]; yy=y
                if nuisance=="fixedoffset":
                    coef=fit(x,y)
                    adjustment=multiply(z,coef[3:])
                    yy=[[a[0]-b[0]] for a,b in zip(y,adjustment)]
                    x=[a+b for a,b in zip(d,f)]
                p=len(x[0]); inv=inverse(multiply(transpose(x),x)); beta=fit(x,yy)
                wd=[row+[Decimal(0)]*(p-2) for row in d]
                fd=[[Decimal(0)]*2+row+[Decimal(0)]*(p-3) for row in f]
                aa=multiply(multiply(transpose(wd),h),wd)
                ff=multiply(multiply(transpose(fd),h),fd)
                af=multiply(multiply(transpose(wd),h),fd)
                af=[[(af[i][j]+af[j][i])/2 for j in range(p)] for i in range(p)]
                total=[[aa[i][j]+ff[i][j]+2*af[i][j] for j in range(p)] for i in range(p)]
                targets=[aa,ff,af,total]
                plugin=[quadratic(a,beta) for a in targets]
                if nuisance=="joint":
                    lines.append(f"matrix anchor_plugin_{basis} = ("+",".join(f"{float(v):.17g}" for v in plugin)+")")
                for deletion,width in [("observation",1),("match",2)]:
                    correction=[Decimal(0)]*4
                    for first in range(0,n,width):
                        block=list(range(first,first+width)); keep=[i for i in range(n) if i not in block]
                        xm=[x[i] for i in block]; ym=[yy[i] for i in block]
                        deleted=fit([x[i] for i in keep],[yy[i] for i in keep])
                        fitted=multiply(xm,deleted)
                        residual=[[a[0]-b[0]] for a,b in zip(ym,fitted)]
                        score=multiply(xm,inv)
                        for j,a in enumerate(targets):
                            kernel=multiply(multiply(score,a),transpose(score))
                            correction[j]+=multiply(multiply(transpose(ym),kernel),residual)[0][0]
                    corrected=[a-b for a,b in zip(plugin,correction)]
                    # Keep Stata names within 32 characters.
                    mode="obs" if deletion=="observation" else "match"
                    nuisance_label="joint" if nuisance=="joint" else "offset"
                    lines.append(f"matrix anchor_{nuisance_label}_{mode}_{basis} = ("+",".join(f"{float(v):.17g}" for v in corrected)+")")
    return "\n".join(lines)+"\n"


if __name__ == "__main__":
    FIXTURE.write_text(fixture_text())
